# Generated by Django 4.1.4 on 2023-10-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='user',
        ),
    ]
